# The following redirect is intended for use with most SPA's that handles routing internally.

[[redirects]]
  from = "/invoice"
   to = "/index.html"
  status = 301
  force = false
  query = {id = ":id"}