export const ADD_INVOICE = 'ADD_INVOICE';
export const SAVE_CHANGES = 'SAVE_CHANGES';
export const EDIT = 'EDIT';
export const DELETE = 'DELETE';
export const PAID = 'PAID';
export const CREATE = 'CREATE';
export const DISCARD = 'DISCARD';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_ERRORS = 'SET_ERRORS';

// Quotation action types
export const ADD_QUOTATION = 'ADD_QUOTATION';
export const SAVE_QUOTATION_CHANGES = 'SAVE_QUOTATION_CHANGES';
export const EDIT_QUOTATION = 'EDIT_QUOTATION';
export const DELETE_QUOTATION = 'DELETE_QUOTATION';
export const APPROVE_QUOTATION = 'APPROVE_QUOTATION';
export const CREATE_QUOTATION = 'CREATE_QUOTATION';
export const DISCARD_QUOTATION = 'DISCARD_QUOTATION';
export const TOGGLE_QUOTATION_MODAL = 'TOGGLE_QUOTATION_MODAL';
export const SET_QUOTATION_ERRORS = 'SET_QUOTATION_ERRORS';

// Add SET_QUOTATIONS if it doesn't exist
export const SET_QUOTATIONS = 'SET_QUOTATIONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_FIREBASE_ERROR = 'SET_FIREBASE_ERROR';

// Internal PO action types
export const ADD_INTERNAL_PO = 'ADD_INTERNAL_PO';
export const SAVE_INTERNAL_PO_CHANGES = 'SAVE_INTERNAL_PO_CHANGES';
export const EDIT_INTERNAL_PO = 'EDIT_INTERNAL_PO';
export const DELETE_INTERNAL_PO = 'DELETE_INTERNAL_PO';
export const PAID_INTERNAL_PO = 'PAID_INTERNAL_PO';
export const CREATE_INTERNAL_PO = 'CREATE_INTERNAL_PO';
export const DISCARD_INTERNAL_PO = 'DISCARD_INTERNAL_PO';
export const TOGGLE_INTERNAL_PO_MODAL = 'TOGGLE_INTERNAL_PO_MODAL';
export const SET_INTERNAL_PO_ERRORS = 'SET_INTERNAL_PO_ERRORS';
export const SET_INTERNAL_POS = 'SET_INTERNAL_POS';
